# Use the official Python base image
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the application file into the container
COPY app .

# Run the application
CMD ["python", "app.py"]